export const DEFAULT_LOCAL_APPLICATION_PUBLIC_HTTP_URL = "http://127.0.0.1:18092";
export const DEFAULT_LOCAL_PLATFORM_API_GATEWAY_HTTP_URL = "http://127.0.0.1:3900";

export const VITE_SDKWORK_MANAGER_APPLICATION_PUBLIC_HTTP_URL =
  "VITE_SDKWORK_MANAGER_APPLICATION_PUBLIC_HTTP_URL";
export const VITE_SDKWORK_MANAGER_PLATFORM_API_GATEWAY_HTTP_URL =
  "VITE_SDKWORK_MANAGER_PLATFORM_API_GATEWAY_HTTP_URL";
export const VITE_SDKWORK_MANAGER_VITE_DEV_PROXY_ENABLED =
  "VITE_SDKWORK_MANAGER_VITE_DEV_PROXY_ENABLED";

export const SDKWORK_APP_API_PREFIX = "/app/v3/api";
export const SDKWORK_BACKEND_API_PREFIX = "/backend/v3/api";
export const MANAGER_APP_API_SEGMENT = "manager";
