//! Generated gateway bootstrap for sdkwork-manager.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_manager_service_host::ManagerServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<ManagerServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    let iam = sdkwork_iam_gateway_assembly::assemble_application_business_router().await;
    router = router.merge(iam.router);
    router = router.merge(sdkwork_routes_manager_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_manager_backend_api::gateway_mount(host).await);
    ApplicationAssembly { router }
}
