import { useEffect, useState } from "react";
import type { SdkworkIamPermission, SdkworkIamPermissionController, SdkworkIamPolicy, SdkworkIamRole } from "@sdkwork/iam-pc-admin-permission";

type Kind = "role" | "permission" | "policy";
type Item = SdkworkIamRole | SdkworkIamPermission | SdkworkIamPolicy;
type Props = { controller: SdkworkIamPermissionController; description: string; kind: Kind; title: string };
type Draft = { action: string; code: string; name: string; resource: string; status: string };
const emptyDraft: Draft = { action: "", code: "", name: "", resource: "", status: "" };
const idOf = (item: Item, kind: Kind) => kind === "role" ? (item as SdkworkIamRole).roleId : kind === "permission" ? (item as SdkworkIamPermission).permissionId : (item as SdkworkIamPolicy).policyId;
const errorMessage = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback;

export function IamCatalogWorkspace({ controller, description, kind, title }: Props) {
  const [items, setItems] = useState<readonly Item[]>([]); const [draft, setDraft] = useState<Draft>(emptyDraft); const [editing, setEditing] = useState<string>(); const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>();
  const refresh = async () => setItems(kind === "role" ? await controller.listRoles() : kind === "permission" ? await controller.listPermissions() : await controller.listPolicies());
  useEffect(() => { void refresh().catch((reason) => setError(errorMessage(reason, "Unable to load this access catalog."))); }, [controller, kind]);
  const save = async () => { setError(undefined); try { if (editing) { if (kind === "role") await controller.updateRole(editing, draft); if (kind === "permission") await controller.updatePermission(editing, draft); if (kind === "policy") await controller.updatePolicy(editing, draft); } else { if (kind === "role") await controller.createRole(draft); if (kind === "permission") await controller.createPermission(draft); if (kind === "policy") await controller.createPolicy(draft); } setDraft(emptyDraft); setEditing(undefined); setNotice("Changes saved."); await refresh(); } catch (reason) { setError(errorMessage(reason, "This change could not be saved.")); } };
  const remove = async (item: Item) => { const id = idOf(item, kind); if (!window.confirm("Delete this catalog entry? This cannot be undone.")) return; try { if (kind === "role") await controller.deleteRole(id); if (kind === "permission") await controller.deletePermission(id); if (kind === "policy") await controller.deletePolicy(id); setNotice("Catalog entry deleted."); await refresh(); } catch (reason) { setError(errorMessage(reason, "This catalog entry could not be deleted.")); } };
  const permission = kind === "permission";
  return <section className="manager-iam-workspace"><header className="manager-iam-workspace__header"><div><p className="manager-iam-workspace__eyebrow">Access control / {kind}</p><h2>{title}</h2><p>{description}</p></div><span className="manager-iam-workspace__count">{items.length} records</span></header>{error ? <p className="manager-iam-workspace__notice manager-iam-workspace__notice--error" role="alert">{error}</p> : null}{notice ? <p className="manager-iam-workspace__notice" role="status">{notice}</p> : null}<form className="manager-iam-editor" onSubmit={(event) => { event.preventDefault(); void save(); }}><div className="manager-iam-editor__heading"><h3>{editing ? `Edit ${kind}` : `Create ${kind}`}</h3>{editing ? <button className="manager-iam-button manager-iam-button--quiet" onClick={() => { setDraft(emptyDraft); setEditing(undefined); }} type="button">Cancel edit</button> : null}</div><label>Name<input onChange={(event) => setDraft({ ...draft, name: event.target.value })} required value={draft.name} /></label><label>Code<input onChange={(event) => setDraft({ ...draft, code: event.target.value })} required={permission} value={draft.code} /></label>{permission ? <><label>Resource<input onChange={(event) => setDraft({ ...draft, resource: event.target.value })} value={draft.resource} /></label><label>Action<input onChange={(event) => setDraft({ ...draft, action: event.target.value })} value={draft.action} /></label></> : <label>Status<input onChange={(event) => setDraft({ ...draft, status: event.target.value })} value={draft.status} /></label>}<button className="manager-iam-button manager-iam-button--primary" disabled={!draft.name || (permission && !draft.code)} type="submit">{editing ? "Save changes" : `Create ${kind}`}</button></form><div className="manager-iam-table-wrap"><table className="manager-iam-table"><thead><tr><th>Name</th><th>Code</th>{permission ? <><th>Resource</th><th>Action</th></> : <th>Status</th>}<th aria-label="Actions" /></tr></thead><tbody>{items.length ? items.map((item) => { const details = item as Item & Partial<Draft>; return <tr key={idOf(item, kind)}><td><strong>{item.name}</strong></td><td><code>{details.code || "-"}</code></td>{permission ? <><td>{details.resource || "-"}</td><td>{details.action || "-"}</td></> : <td>{details.status || "-"}</td>}<td className="manager-iam-table__actions"><button className="manager-iam-button manager-iam-button--quiet" onClick={() => { setEditing(idOf(item, kind)); setDraft({ action: details.action || "", code: details.code || "", name: item.name, resource: details.resource || "", status: details.status || "" }); }} type="button">Edit</button><button className="manager-iam-button manager-iam-button--danger" onClick={() => void remove(item)} type="button">Delete</button></td></tr>; }) : <tr><td colSpan={permission ? 5 : 4}>No {kind} entries have been created.</td></tr>}</tbody></table></div></section>;
}